### ISSUE TITLE
Use input STL or OBJ mesh file as input

### ISSUE THREAD

**Issue by yvanblanchard** [mauriciopoppe/quickhull3d#25]
Hello,
would it be possible to input STL or OBJ mesh file as input (TEXT or binary format, taking only the vertices) ?
Thank you

**Comment by z3dev** [comment]
Not directly. The vertices need to be converted, and unique as well.

Take a look at JSCAD www.openjscad.xyz

**Comment by mauriciopoppe** [comment]
Agreed with https://github.com/mauriciopoppe/quickhull3d/issues/25#issuecomment-1547013254, the input needs to be an array of unique points.
