### ISSUE TITLE
maintain UV textureCoordinates

### ISSUE THREAD

**Issue by dmorehead** [mauriciopoppe/quickhull3d#26]
I'm thinking of using quickhull3d to optimize the accumulated geometry of a voxel-like builder, where each cube has separate texureCoordinates from a 16x16 texturemap. I wonder how (if possible) to transfer those unique texCoords to a set of points generated by quickull3d? Thanks in advance for your thoughts.
liiea5sd](https://github.com/mauriciopoppe/quickhull3d/assets/20470493/6d15a13d-a886-4956-b388-c8104f76e762)

**Comment by mauriciopoppe** [comment]
hi @dmorehead and sorry for the late reply.

What's the current definition of geometry for a voxel? I think that if it's like a cube then you'd have at least 3 numbers (x,y,z,d) where d would be depth, width, heigh. How do you represent the geometry with a data structure?

**Comment by dmorehead** [comment]
Hi, thanks for the reply.
Its inspired by voxels, but allows multiple sizes, shapes, textures. the editor combines individual shapes which become a single indexedTriangleSet with points, indexes, texCoords. I'd like to optimize by eliminating internal faces from the individual shapes. i.e. if 2 cubes are touching, eliminate the internal / overlapping faces.

indexes='0,1,2,0,2,3,4,5,6,4,6,7,8,9,10,8,10,11,12,13,14,12,14,15,16,17,18,16,18,19,20,21,22,20,22,23,24,25,26,26,25,27,25,28,27,28,29,27,29,30,27,27,30,31,32,33,34,34,33,35,35,33,36,36,33,37,37,33,38,33,39,38,40,41,42,41,43,42,44,45,46,45,47,46,48,49,50,49,51,50,52,53,54,54,53,55,53,56,55,55,56,57,56,58,57,57,58,59,58,60,59,59,60,61,60,62,61,61,62,63,62,64,63,63,64,65,66,67,68,68,67,69,69,67,70,70,67,71,71,67,72,72,67,73,73,67,74,67,75,74,76,77,78,78,77,79,77,80,79,80,81,79,81,82,79,82,83,79,83,84,79,79,84,85,86,87,88,87,89,88,90,91,92,91,93,92,92,93,94,93,95,94,94,95,96,95,97,96,96,97,98,97,99,98,98,99,100,99,101,100,100,101,102,101,103,102,104,105,106,105,107,106,108,109,110,109,111,110,112,113,114,113,115,114,116,117,118,117,119,118,120,121,122,120,122,123,124,125,126,124,126,127,128,129,130,128,130,131,132,133,134,132,134,135,136,137,138,136,138,139,140,141,142,140,142,143,144,145,146,147,148,149,150,151,152,150,152,153,154,155,156,154,156,157,158,159,160,158,160,161'

points='0,0,0,100,0,0,100,100,0,0,100,0,0,100,0,100,100,0,100,100,-100,0,100,-100,0,100,-100,100,100,-100,100,0,-100,0,0,-100,0,0,-100,100,0,-100,100,0,0,0,0,0,100,0,0,100,0,-100,100,100,-100,100,100,0,0,0,-100,0,0,0,0,100,0,0,100,-100,100,99.99990000000001,-100,125.8819,96.59249999999999,-100,100,0,-100,200,0,-100,150,86.6025,-100,170.7106,70.7106,-100,186.6025,50,-100,196.5925,25.8819,-100,100,0,0,200,0,0,100,99.99990000000001,0,125.8819,96.59249999999999,0,150,86.6025,0,170.7106,70.7106,0,186.6025,50,0,196.5925,25.8819,0,100,0,-100,100,0,0,100,99.99990000000001,-100,100,99.99990000000001,0,200,0,-100,200,0,0,100,0,-100,100,0,0,100,99.99990000000001,-100,100,99.99990000000001,-100,100,99.99990000000001,0,100,99.99990000000001,0,100,99.99990000000001,0,125.8819,96.59249999999999,0,100,99.99990000000001,-100,125.8819,96.59249999999999,-100,150,86.6025,0,150,86.6025,-100,170.7106,70.7106,0,170.7106,70.7106,-100,186.6025,50,0,186.6025,50,-100,196.5925,25.8819,0,196.5925,25.8819,-100,200,0,0,200,0,-100,-100,100,-100,0,100,-100,-100,75,-100,-80.5886,72.4444,-100,-62.5,64.9519,-100,-46.967,53.032999999999994,-100,-35.0481,37.5,-100,-27.5556,19.4114,-100,-25,0,-100,0,0,-100,-100,75,0,-80.5886,72.4444,0,-100,100,0,0,100,0,-62.5,64.9519,0,-46.967,53.032999999999994,0,-35.0481,37.5,0,-27.5556,19.4114,0,-25,0,0,0,0,0,-100,75,0,-100,75,-100,-100,75,0,-100,75,-100,-25,0,-100,-25,0,0,-27.5556,19.4114,-100,-27.5556,19.4114,0,-35.0481,37.5,-100,-35.0481,37.5,0,-46.967,53.032999999999994,-100,-46.967,53.032999999999994,0,-62.5,64.9519,-100,-62.5,64.9519,0,-80.5886,72.4444,-100,-80.5886,72.4444,0,-100,75,-100,-100,75,0,-100,100,0,-100,100,-100,-100,75,0,-100,75,-100,0,0,-100,0,0,0,-25,0,-100,-25,0,0,0,100,0,0,100,-100,-100,100,0,-100,100,-100,0,0,-100,0,100,-100,0,0,0,0,100,0,100,100,-100,50,100,-100,50,150,-100,100,125.02799999999999,-100,100,125.02799999999999,-100,50,150,-100,50,150,-50,100,125.02799999999999,-50,100,125.02799999999999,-50,50,150,-50,50,100,-50,100,100,-50,100,100,-50,50,100,-50,50,100,-100,100,100,-100,50,100,-100,50,100,-50,50,150,-50,50,150,-100,100,100,-50,100,100,-100,100,125.02799999999999,-100,100,125.02799999999999,-50,199.9999998301276,0,1.6987241835408897,200.0000001698724,0,50.00000016987242,199.9999998301276,50,1.698724183540889,249.9999998301276,50,-1.6987241835408,250.0000001698724,0,49.99999983012758,249.9999998301276,0,-1.6987241835408,249.9999998301276,0,-1.6987241835408,250.0000001698724,0,49.99999983012758,200.0000001698724,0,50.00000016987242,199.9999998301276,0,1.6987241835408895e-7,200.0000001698724,0,50.00000016987242,250.0000001698724,0,49.99999983012758,249.9999998301276,50,-1.6987241835408,199.9999998301276,50,1.6987241835408,249.9999998301276,0,-1.6987241835408,199.9999998301276,0,1.69872418354,199.9999998301276,50,1.69872418354088,249.9999998301276,50,-1.69872418354088
![voxel](https://github.com/mauriciopoppe/quickhull3d/assets/20470493/110a912f-360c-46d9-9fa2-a0ead2c02eaf)
'

texcoords='0.00390625,0.75390625,0.24609375,0.75390625,0.24609375,0.99609375,0.00390625,0.99609375,0.00390625,0.99609375,0.24609375,0.99609375,0.24609375,0.75390625,0.00390625,0.75390625,0.24609375,0.99609375,0.00390625,0.99609375,0.00390625,0.75390625,0.24609375,0.75390625,0.00390625,0.99609375,0.24609375,0.99609375,0.24609375,0.75390625,0.00390625,0.75390625,0.24609375,0.75390625,0.00390625,0.75390625,0.00390625,0.99609375,0.24609375,0.99609375,0.24609375,0.75390625,0.00390625,0.75390625,0.00390625,0.99609375,0.24609375,0.99609375,0.49609375,0.7460935078125,0.4334110234375,0.7378412109375,0.49609375,0.50390625,0.25390625,0.50390625,0.375,0.7136466796875001,0.32484151562499997,0.675158484375,0.2863533203125,0.625,0.2621587890625,0.5665889765625,0.25390625,0.50390625,0.49609375,0.50390625,0.25390625,0.7460935078125,0.3165889765625,0.7378412109375,0.375,0.7136466796875001,0.42515848437500003,0.675158484375,0.4636466796875,0.625,0.4878412109375,0.5665889765625,0.49609375,0.50390625,0.25390625,0.50390625,0.49609375,0.7460935078125,0.25390625,0.7460935078125,0.49609375,0.74609375,0.49609375,0.50390625,0.25390625,0.74609375,0.25390625,0.50390625,0.3573404140625,0.6023518359375,0.3573404140625,0.6023518359375,0.3573404140625,0.6478758203125,0.3573404140625,0.6478758203125,0.289373640625,0.74609375,0.289373640625,0.7106261171875,0.4606261171875,0.74609375,0.4606261171875,0.7106261171875,0.289373640625,0.6693234609375001,0.4606261171875,0.6693234609375001,0.289373640625,0.625,0.4606261171875,0.625,0.289373640625,0.5806765390625,0.460626359375,0.5806765390625,0.289373640625,0.5393738828125,0.460626359375,0.5393738828125,0.289373640625,0.50390625,0.460626359375,0.50390625,0.99609375,0.99609375,0.75390625,0.99609375,0.99609375,0.935546875,0.949081765625,0.92935753125,0.9052734375,0.9112116328125,0.867654453125,0.882345546875,0.8387883671875,0.8447265625,0.82064246875,0.800918234375,0.814453125,0.75390625,0.75390625,0.75390625,0.75390625,0.935546875,0.800918234375,0.92935753125,0.75390625,0.99609375,0.99609375,0.99609375,0.8447265625,0.9112116328125,0.882345546875,0.882345546875,0.9112116328125,0.8447265625,0.92935753125,0.800918234375,0.935546875,0.75390625,0.99609375,0.75390625,0.8573404140625001,0.8978758203125,0.8573404140625001,0.8523518359375,0.8573404140625001,0.8978758203125,0.8573404140625001,0.8523518359375,0.7608316015625,0.75390625,0.9891683984374999,0.75390625,0.7608316015625,0.7893738828125,0.9891683984374999,0.7893738828125,0.7608316015625,0.83067678125,0.9891683984374999,0.83067678125,0.7608316015625,0.875,0.9891683984374999,0.875,0.7608316015625,0.9193234609375001,0.9891683984374999,0.9193234609375001,0.7608316015625,0.960626359375,0.9891683984374999,0.960626359375,0.7608316015625,0.99609375,0.9891683984374999,0.99609375,0.75390625,0.99609375,0.99609375,0.99609375,0.75390625,0.935546875,0.99609375,0.935546875,0.99609375,0.99609375,0.99609375,0.75390625,0.935546875,0.99609375,0.935546875,0.75390625,0.99609375,0.99609375,0.99609375,0.75390625,0.75390625,0.99609375,0.75390625,0.75390625,0.75390625,0.75390625,0.75390625,0.99609375,0.99609375,0.75390625,0.99609375,0.99609375,0.00390625,0.00390625,0.24609375,0.00390625,0.24609375,0.24609375,0.00390625,0.125135625,0.00390625,0.00390625,0.24609375,0.00390625,0.24609375,0.24609375,0.00390625,0.24609375,0.24609375,0.125135625,0.00390625,0.24609375,0.00390625,0.00390625,0.24609375,0.00390625,0.00390625,0.00390625,0.24609375,0.00390625,0.24609375,0.24609375,0.00390625,0.24609375,0.24609375,0.00390625,0.00390625,0.00390625,0.00390625,0.24609375,0.24609375,0.24609375,0.24609375,0.00390625,0.00390625,0.00390625,0.00390625,0.125135625,0.24609375,0.125135625,0.75390625,0.50390625,0.99609375,0.50390625,0.75390625,0.74609375,0.99609375,0.74609375,0.75390625,0.50390625,0.99609375,0.50390625,0.75390625,0.685546875,0.99609375,0.685546875,0.99609375,0.50390625,0.75390625,0.50390625,0.75390625,0.50390625,0.99609375,0.50390625,0.99609375,0.74609375,0.75390625,0.74609375,0.99609375,0.50390625,0.75390625,0.50390625,0.75390625,0.74609375,0.99609375,0.74609375'

**Comment by mauriciopoppe** [comment]
Marking as stale, please reopen with a simplified test case if needed.
