### ISSUE TITLE
Incorrect results for objects with duplicate vertices

### ISSUE THREAD

**Issue by codand** [mauriciopoppe/quickhull3d#38]
After upgrading from version 3.0.0 to version 3.1.0, I've started getting incorrect results for hulls generated from triangulated meshes. These meshes are in triangle-soup format, so they have duplicate vertices. I'm able to repro the failure in my application by translating a cube. In some translations, it works correctly, but in other translations, it gives garbage faces.

The cube in question
![image](https://github.com/user-attachments/assets/31025b95-4599-4ae3-9793-dd5ab8b2dded)

Expected result (3.0.0) - 6 faces
![image](https://github.com/user-attachments/assets/b77ae6a5-5d9c-4707-9d00-1899eecaa7bd)

Actual result (3.1.0) - 1 face
![image](https://github.com/user-attachments/assets/2d1d6a8f-cc03-45ca-9568-98ce1160ee2f)

Minimal repro: https://jsfiddle.net/tqoazr9k/1/

**Comment by mauriciopoppe** [comment]
Thanks a lot for the detailed report, I fixed it in https://github.com/mauriciopoppe/quickhull3d/pull/40, please check the description for an explanation of the problem.

**Comment by mauriciopoppe** [comment]
Fix released in https://github.com/mauriciopoppe/quickhull3d/releases/tag/v3.1.1

**Comment by codand** [comment]
Thank you! :smile:
