### ISSUE TITLE
sometimes not working.

### ISSUE THREAD

**Issue by Lootoe** [mauriciopoppe/quickhull3d#39]
In most cases, the result is good, but occasionally there are exceptions.
![企业微信截图_20240726100049](https://github.com/user-attachments/assets/650914c8-6b39-4778-8b1d-9a2e0a85347d)
![企业微信截图_20240726100101](https://github.com/user-attachments/assets/59869b58-2319-4d90-8cca-7f7f444ed25f)

**Comment by mauriciopoppe** [comment]
I've fixed an issue in #40 that produced bad results for polygons where the origin was not inside the polygon. Please use https://github.com/mauriciopoppe/quickhull3d/releases/tag/v3.1.1.

Also to debug this issue further if it still exists please provide a reproducible test case.

**Comment by Lootoe** [comment]
Oh my god, thank you.Your speed is really fast, just like the Flash.

**Comment by Lootoe** [comment]
The problem has been solved.
