### ISSUE TITLE
Likely a typo

### ISSUE THREAD

**Issue by WestLangley** [mauriciopoppe/quickhull3d#6]
```javascript
if (vertex !== v0 && vertex !== v1 && vertex !== v3 && vertex !== v3) {
```

https://github.com/mauriciopoppe/quickhull3d/blob/master/lib/QuickHull.js#L383

**Comment by mauriciopoppe** [comment]
Yes indeed, thank you for the report, also big kudos for all the work you do on threejs and for the awesome answers on stackoverflow 🥇
