### ISSUE TITLE
bug in doAdjacentMerge

### ISSUE THREAD

**Issue by akshaal** [mauriciopoppe/quickhull3d#7]
If mergeType === MERGE_NON_CONVEX, then doAdjacentMerge doesn't really do anything, it just sets 'merge' variable to true and that's all. That's because, "if (merge) {...}" code block is in the wrong scope, it should be one level up (in while-loop, not in the else part of "if (mergeType === MERGE_NON_CONVEX)"). Original QuickHull3D.java code looks OK, the problem is javascript-version specific:
```
do {
   if (mergeType === MERGE_NON_CONVEX) {
       ....
      merge = true
   } else {
      .....
      if (merge) {
            debug('face merge')
       ....
       }
    }
} while(...)
```

**Comment by mauriciopoppe** [comment]
Thank you for the report!

Fixed in https://github.com/mauriciopoppe/quickhull3d/releases/tag/v2.0.4
